# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

	# This box was built on 18-11-2015 with using the boxcutter packer configuration with puppet installed

	config.vm.box = "ubuntu/trusty64"
	#config.vm.box = "besquared/ubuntu1510"
	#config.vm.box_url = "https://besquared.s3.amazonaws.com/public/vagrant/ubuntu1510-puppetlatest-0.1.0.box"
	#config.vm.box_download_checksum_type = "sha256"
	#config.vm.box_download_checksum = "9dcd36477a43c3022d765cb8be9a58466c936994a627a5a2c1970d497d44d88d"
	
	# Letting Vagrant manage the hostname does not work at the moment for Ubuntu 15.10 (Wily Werewolf)
	# config.vm.hostname = "dev.local"
	
	config.vm.boot_timeout = 150
	
	# config.vm.synced_folder "../data", "/vagrant_data"
	
	# config.vm.network "public_network"
	#config.vm.network "forwarded_port", guest: 80, host: 8080
	config.vm.network "private_network", type: "dhcp"
		
	config.vm.provider "virtualbox" do |vb|
		vb.name = "dev"
		
		# Display the VirtualBox GUI when booting the machine
		vb.gui = false

		vb.memory = "512"
		vb.cpus = "1"
	end
	
	config.vm.post_up_message = "Virtual machine is running!"

	#
	# View the documentation for the provider you are using for more
	# information on available options.

	# Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
	# such as FTP and Heroku are also available. See the documentation at
	# https://docs.vagrantup.com/v2/push/atlas.html for more information.
	# config.push.define "atlas" do |push|
	#   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
	# end

	# Enable provisioning with a shell script. Additional provisioners such as
	# Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
	# documentation for more information about their specific syntax and use.	
	
	# config.vm.provision "shell", inline: <<-SHELL
	# 	sudo apt-get update -y
	# 	sudo apt-get install -y puppet
	# SHELL
end
